### ISSUE TITLE
Fix standalone services compilation problem

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#102]
The workaround has been made available for this issue but definitely, fix is needed.
Adding to tracker.

> This solution is just a workaround, so I prefer to close it until we implement a proper solution for this problem: https://github.com/polycube-network/polycube/issues/91.

_Originally posted by @mauriciovasquezbernal in https://github.com/polycube-network/polycube/pull/77#issuecomment-477319891_

**Comment by mauriciovasquezbernal** [comment]
This is a duplicated of https://github.com/polycube-network/polycube/issues/91.

**Comment by frisso** [comment]
Closing; refer to #91.
