### ISSUE TITLE
[BUG] polycubectl - "no cube found named xxx"

### ISSUE THREAD

**Issue by gianlu33** [polycube-network/polycube#135]
## Describe the bug
Some commands do not work using the notation 
`polycubectl <service_type> <service_name> <add/remove/set/..>`

## To Reproduce
1. `polycubectl bridge add b1 stp-enabled=true` -> ok
2. `polycubectl bridge b1 ports add p1` -> ok
3. `polycubectl bridge b1 stp 1 set priority=28672` -> error

Output after command 3. -> `No cube found named bridge`

## Additional context
If i omit <service_type>, the command works correctly
E.g. `polycubectl b1 stp 1 set priority=28672` -> ok

Strangely, this bug does not happens everytime (for example command 2. above does not present any problem)

**Comment by mauriciovasquezbernal** [comment]
Thanks @gianlu33 for reporting this, it was because an old workaround we have in the code.
Already opened a PR to solve this.

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/polycube-network/polycube/pull/136
