### ISSUE TITLE
[BUG] pcn-iptables build instruction is incorrect

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#138]
## Describe the bug
Build procedure for pcn-iptables may need a review.
 
https://github.com/polycube-network/polycube/tree/master/src/components/iptables#steps-to-install-pcn-iptables

## To Reproduce
1. Follow the instruction from the above link and it won't work, as the build directory isn't there.

## Expected behavior
1. Needs a clear and easy to follow instruction to build and install.

## Please tell us about your environment: 
1. OS details: `Ubuntu 18.04 LTS` 
2. Kernel details: `4.15.0-20-generic x86_64`
3. Polycube Version: N/A
4. Polycube Log: N/A

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/polycube-network/polycube/pull/139
