### ISSUE TITLE
Automate all the manual test procedure

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#165]
Also, we might want to think of automating this procedure, rather than manual.

_Originally posted by @acloudiator in https://github.com/polycube-network/polycube/pull/160#issuecomment-506518016_

**Comment by acloudiator** [comment]
@mauriciovasquezbernal Would you please help to add some details of the current manual test procedure, we will plan to make it automated.

**Comment by mauriciovasquezbernal** [comment]
Tests are automatically run in Jenkins, http://130.192.225.104:8080/job/polycube-test/, but the result of those tests is not shown in github. AFAIK this is quite complicated to setup.

**Comment by acloudiator** [comment]
> Tests are automatically run in Jenkins, http://130.192.225.104:8080/job/polycube-test/, but the result of those tests is not shown in github. AFAIK this is quite complicated to setup.

As long as it's automated, it should be fine. The only thing to bear is that all these tests should be executed with each PR and block the PR to merge if it fails.

**Comment by palexster** [comment]
Fixed by #235, #239, #231 and #197.
