### ISSUE TITLE
[BUG] auto-install script fails on freshly installed server

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#173]
## Describe the bug
Instruction for [auto-install](https://github.com/polycube-network/polycube/blob/master/Documentation/installation.rst#automatic-installation) is failing with an error. It says, "no package found" (for gcc and g++)

## To Reproduce
1. Install a fresh Ubuntu 18.04 LTS - x86_64 operating system
2. Follow [auto-install](https://github.com/polycube-network/polycube/blob/master/Documentation/installation.rst#automatic-installation) instruction

## Expected behavior
Following the instruction on a freshly installed OS (even with minimal packages) should succeed.

## Please tell us about your environment: 
1. OS details: `Ubuntu 18.04 LTS` 
2. Kernel details: `4.15.0-20-generic`
3. Polycube Version: NA
4. Polycube Log: NA

## Additional context
The script tries to use the missing packages with `make` but couldn't find it. 
Inclusion of the missing packages worked for me.

https://github.com/polycube-network/polycube/blob/master/scripts/install.sh#L64
`$SUDO apt install -y wget gnupg2 gcc g++`

**Comment by mauriciovasquezbernal** [comment]
Hello @acloudiator , could you please share the full log?, that error looks weird to me because gcc and g++ are included in the build-essencial package that is installed.  I just tried on a fresh installation and it worked for me without major problems.

**Comment by acloudiator** [comment]
@mauriciovasquezbernal unfortunately, the terminal scrollback wasn't set, so it rolled over.
But I believe it won't be any harm to have this package mentioned, it will pass if already installed or install if not present. What say?

**Comment by mauriciovasquezbernal** [comment]
@acloudiator I will not add then until there is a confirmation of the problem, those are already included in `build-essential` so likely there was a different problem in your installation.

**Comment by michelsciortino** [comment]
I've tested this on two new clean Ubuntu 18.04 instances, one with full installation, one with minimal installation.
- Os version:  Ubuntu 18.04
- Kernel version: 4.18.0-15-generic

The installation completes flawlessly on both and Polycube works as expected.

I think this can be closed.

**Comment by palexster** [comment]
Closing.
