### ISSUE TITLE
[Inquiry] Is ppa:longsleep/golang-backports still relevant?!

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#174]
## Describe the bug
Do we still need golang-backports? Or we can use the one with comes with OS repo.
`sudo apt-get install golang-go` ?!
https://github.com/polycube-network/polycube/blob/6e4dbcc2b97cebddb2bc2e2f9324d36b07534ac1/scripts/install.sh#L74

**Comment by mauriciovasquezbernal** [comment]
I think this is needed because otherwise the golang version installed would be behind 1.12 that is required.

**Comment by acloudiator** [comment]
Closing this with an additional link: 
https://github.com/golang/go/wiki/Ubuntu
