### ISSUE TITLE
[INQUIRY] Why we use opensuse source for libyang-dev? 

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#175]
## Describe the query
Shouldn't we use the repo of Ubuntu instead opensuse for libyang-dev?! 
Especially when all our test and support are currently limited to Ubuntu 18.04 LTS.

Repo is available to use with apt `deb http://mirrors.kernel.org/ubuntu disco main universe`

https://github.com/polycube-network/polycube/blob/6e4dbcc2b97cebddb2bc2e2f9324d36b07534ac1/scripts/install.sh#L80

**Comment by mauriciovasquezbernal** [comment]
Is that package available in 18.04 as well? According to my understanding this is only available in disco (19.04).

**Comment by acloudiator** [comment]
> Is that package available in 18.04 as well? According to my understanding this is only available in disco (19.04).

Nice catch! So we can only use ubuntu repo in 19.04.
