### ISSUE TITLE
[Feature Request] - Project Packet Capture

### ISSUE THREAD

**Issue by DavideAG** [polycube-network/polycube#187]
## Project packetcapture

Project aiming at the creation of new transparent service that enables to remotely capture packets from a network interface (or a port in Polycube).
This service can be attached to any port and it should be able to capture packets crossing that interface, exporting this data though the Polycube REST service.
A minimal set of configuration options should be available through the web interface.
A similar project is PacketBeat (https://www.elastic.co/products/beats/packetbeat), which focus on network statistics instead of raw packet.

**Comment by frisso** [comment]
Done with #273
