### ISSUE TITLE
[Feature Request] - Project Polycube Benchmarking

### ISSUE THREAD

**Issue by s41m0n** [polycube-network/polycube#191]
## Project Polycube Benchmarking
Project aiming at the creation of a minimal benchmarking infrastructure in Polycube. In order to achieve that goal, a class which enables the dynamic gathering of the timestamp of specific events should be developed. Moreover, the class should be used across the entire Polycube framework.

### Functional Requirements
Class to monitor the time taken by certain events. This functionality could be active or not, depending by the user willing. If enabled by default, an easy way to disable it should be provided.

### Non-Functional Requirements
- Usability: the programmer should be able to use it without learning too much (i.e. just by adding a flag to a command);
- Performance: the overhead introduced by this framework should be as little as possible, leaving all the functionalities as efficient as they are;
- Integrability: the project should pollute the already developed code as little as possible;
- Scalability: the framework should work not only with all the already present functions, but also with the future ones (it should be function-independent).

### Deadline
Indicatively the end of August 2019.

**Comment by s41m0n** [comment]
Solution proposal v0.1 available [here](https://github.com/s41m0n/Cplus-Profiler).

**Comment by s41m0n** [comment]
Multiple git rebase to fix missing item/wrong paths.
Last thing to decide is whether to insert the framework activation DEFINE in a global config file or leave it locally into each file which could potentially use it.

Advantage: if I have 10 sources which uses the framework but i don't want to activate it on 3 of them I just don't insert the define in these 3 files.

Disadvantage: programmer should remember to insert the define on each file.

We don't consider to insert the define in the profiler framework itself since it has to be independent by user will.

**Comment by frisso** [comment]
Merged with #215. 
Thanks @s41m0n , very good work!

**Comment by s41m0n** [comment]
I am very glad to have developed this framework in such an important project. Thanks for all the support, I hope to collaborate together again hereafter.
