### ISSUE TITLE
[BUG] polycubectl does not show the usage example

### ISSUE THREAD

**Issue by frisso** [polycube-network/polycube#193]
## Describe the bug
When asking help for a specific command to polycubectl, it should show also the usage example of that field, if present. Currently, only the description of that field is shown.

## To Reproduce
1. Run polycubed
2. Type the following commands: 
`   polycubectl transparenthelloworld add trh1`
`   polycubectl attach trh1 enp0s3     # enp0s3 is your current physical interface`
`   polycubectl trh1 set ?`
3. See the following output:
`Keyword                Type     Description`
` loglevel=value         string   Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)`
` ingress-action=value   string   Action performed on ingress packets`
` egress-action=value    string   Action performed on egress packets`

4. I should see the following:
`Keyword                Type     Description`
` loglevel=value         string   Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)`
` ingress-action=value   string   Action performed on ingress packets (example: DROP/PASS/SLOWPATH (default: PASS))`
` egress-action=value    string   Action performed on egress packets (example: DROP/PASS/SLOWPATH (default: PASS))`

**Comment by pinoOgni** [comment]
Hi @frisso, do you want something as described in the issue (Keyword Type Description and the example together with Description, inside round brackets) or an extra column with Example would also be fine? Something like that:
```
Keyword                Type     Description                                                                                    Example
loglevel=value         string   Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)   
ingress-action=value   string   Action performed on ingress packets                                                            DROP/PASS/SLOWPATH (default: PASS)
egress-action=value    string   Action performed on egress packets                                                             DROP/PASS/SLOWPATH (default: PASS)
```
