### ISSUE TITLE
Update automatic code generation tools

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#2]
https://github.com/polycube-network/swagger-codegen/ is behind last changes we did to polycube.

AFAIK this as the missing changes:
- [x] Ports constructor
- [x] Ports::{create, get, getEntry, remove, removeEntry}
- [x] packet_in signature
- [x] remove TYPE_ from TYPE_{TC, XDP_SKB, XDP_DRV}
- [x] egress_code argument always required in Cube constructor
- [x] Cube is templated: cube inherits from Cube<Ports>
- [x] ports_ is not anymore present on service class (not sure if this is part of the code generator)
- [x] CMakeList.txt on src/
- [x] create service_dp.c instead of service_dp.h
- [x] do not include datamodel in service-lib.cpp

Probably we should adopt a policy that a PR that affects code generation cannot be merged into polycube until the generation tools are updated

- Mauricio

**Comment by mauriciovasquezbernal** [comment]
solved by:
https://github.com/polycube-network/pyang-swagger/pull/3
https://github.com/polycube-network/swagger-codegen/pull/3
