### ISSUE TITLE
[BUG] send_packet_out() can cause a segmentation fault if used in a transparent service

### ISSUE THREAD

**Issue by DavideAG** [polycube-network/polycube#212]
## Describe the bug
send_packet_out () can cause a segmentation fault if used in a transparent service if the parent does not exist

## To Reproduce
Use the tutorial 1 configuration (https://polycube.readthedocs.io/en/latest/tutorials/tutorial1/tutorial1.html)
1. create a new transparent service that uses send_packet_out
2. attach it to veth1
3. execute a ping
4. segmentation fault

## Expected behavior
the service should indicate that the parent does not exist

## Please tell us about your environment: 
1. OS details: Ubuntu 18.04
2. Kernel details: 5.15.0-55-generic
3. Polycube Version: 0.1.0-beta+
4. Polycube Log: "Segmentation Fault"

## Additional context
you need to check if the father exists.
Like https://github.com/polycube-network/polycube/blob/b80ce020a445aec11088fd8b69e16b1956f0b36c/src/polycubed/src/port.cpp#L205

The error is here:
https://github.com/polycube-network/polycube/blob/06f9bb43af8646a620672f56c0e75026a91f2614/src/polycubed/src/transparent_cube.cpp#L103

**Comment by goldenrye** [comment]
This bug will be fixed by the commit under issue 218
