### ISSUE TITLE
[BUG](pcn-k8s) Experiencing very low speed connection from within the pods

### ISSUE THREAD

**Issue by alacuku** [polycube-network/polycube#216]
## Describe the bug
Very low speed connection while downloading from within the pods. "apt get update" usually times out due to low speed. It seems to affect only the outgoing connections toward the internet.

## To Reproduce
Enter any pod in a kubernetes deployment with the pcn-k8s pod network installed and do an "apt update && apt upgrade".

## Please tell us about your environment: 
1. OS details: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

2. Kernel details: Linux k8s-master 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

3. Polycube Version:
polycubectl:
 version: v0.1.0-beta+ [git: (branch/commit): master/06f9bb43]
polycubed:
 version: v0.1.0-beta+ [git: (branch/commit): master/06f9bb43]

**Comment by goldenrye** [comment]
@alacuku The issue cannot be reproduced in my environment, can you double check and exclude the networking configuration issue.

**Comment by alacuku** [comment]
You're right. it was a configuration issue in my environment. Thank you!
