### ISSUE TITLE
bridge show (polycubectl bridge br1 show) should display summarize bridge info

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#24]
vagrant@vagrant:~/polycube/tutorials/tutorial-basic2$ polycubectl bridge br1 show
Method not implemented

vagrant@vagrant:~/polycube/tutorials/tutorial-basic2$ polycubectl bridge br1 show ?

Keyword Type Description
ports list Entry of the ports table
stp list Per-vlan Spanning Tree Protocol Configuration
stpenabled boolean Enable/Disable the STP protocol of the bridge
type string Type of the IOModule (TYPE_TC, TYPE_XDP_SKB, TYPE_XDP_DRV)
uuid string UUID of the IOModule
agingtime integer Aging time of the filtering database
filteringdatabase list Entry associated with the filtering database

vagrant@vagrant:~/polycube/tutorials/tutorial-basic2$ polycubectl bridge br1 show ports ?

Keyword Type Description
string Port Name

vagrant@vagrant:~/polycube/tutorials/tutorial-basic2$ polycubectl bridge br1 show ports
Method not implemented

-Mauricio

**Comment by mauriciovasquezbernal** [comment]
Solved by https://github.com/polycube-network/polycube/pull/125
