### ISSUE TITLE
Make polycubed a system service

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#25]
It is not possible to run two instances of polycubed on the same system, when a second instance is launched, it closes with the following message error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  epoll_ctl(epoll_fd, EPOLL_CTL_ADD, fd, &ev): Bad file descriptor
Aborted
```

That message is not clear enough to recognize the source of the problem.
A mechanism to check if another instance is running would allow printing a more useful message, as:
```
Another instance of polycubed is running PID: ....
```
-Mauricio

**Comment by mauriciovasquezbernal** [comment]
This PR message was quite outdated as the mechanisms mentioned there had been already implemented a time ago. https://github.com/polycube-network/polycube/pull/177 solves the original issue.
