### ISSUE TITLE
[Documentation] Document how to debug polycube

### ISSUE THREAD

**Issue by palexster** [polycube-network/polycube#255]
## Is your feature request related to a problem? Please describe.
In order to simplify the debug of Polycube we should document how it can be run in debug mode.
Hint: 
* Enable the debug (https://stackoverflow.com/questions/7724569/debug-vs-release-in-cmake) and then use gdb gdb --args polycubed (don't forget to install after compiling)

**Comment by frisso** [comment]
Done with #386 .
