### ISSUE TITLE
Add "mirror port" to debug packet flow

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#28]
Commercial devices have the possibility to configure a "mirror port", which takes the traffic on one (or more) ports and duplicates the packets over it. This is used for debugging purposes, as a tcpdump/Wireshark can capture exactly the packet flow that is actually going on in the network.
We should add such a feature to polycube as well: when two services are connected, we should add the possibility to create a mirror port, which turns into creating a hidden iomodule inserted in between the existing two, which takes the packets and duplicate them, and send one to the target iomodule, the other to a tap.
Tcpdump/Wireshark can the attach to that tap and capture the traffic. In this way, we can capture exactly the traffic that is flowing through iomodules, hence possibly detecting where a bug may be.
This feature should be provided by the framework, so it should be included by default in the code automatically produced by our code generation tools.
-Fulvio

**Comment by mauriciovasquezbernal** [comment]
This feature is covered by the span mode present in shadow services. https://github.com/polycube-network/polycube/pull/140.
Unfortunately span mode is not available in non-shadow services, I don't know if this mirror port is still relevant at this point.

**Comment by frisso** [comment]
I would close this, as shadow services should become the 'normal' service mode in the future.
