### ISSUE TITLE
Bridge: Filtering DB does not full support the aging time

### ISSUE THREAD

**Issue by acloudiator** [polycube-network/polycube#29]
Although we have implemented an algorithm that deletes entries when they are not used [1], this implementation presents many limitations and complications.
There is not so much that we can do from our side, this limitation requires an extension to the eBPF maps.
[1] https://github.com/polycube-network/polycube/blob/master/src/services/pcn-bridge/src/Bridge.h#L167-L175
-Mauricio

**Comment by mauriciovasquezbernal** [comment]
I think that the solution implemented to prune too old entries in the bridge is fine and not extensions to the eBPF maps are really needed now, so closing this:
https://github.com/polycube-network/polycube/blob/master/src/services/pcn-bridge/src/Bridge_dp.c#L280
