### ISSUE TITLE
[Feature Request] Move CI/CD to a bot user account

### ISSUE THREAD

**Issue by frisso** [polycube-network/polycube#294]
Currently, CI/CD is linked to a personal GitHub account.
It would be nice to move all the required steps to a bot user account, hence avoiding that secrets are associated to a personal account.

**Comment by palexster** [comment]
Done. Keeping open to check if everything works fine.

**Comment by palexster** [comment]
https://github.com/polycube-network/polycube/pull/284 check ok. Closing,

**Comment by frisso** [comment]
Great, @palexster : thanks!

**Comment by acloudiator** [comment]
> #284 check ok. Closing,

Thank you @palexster !
