### ISSUE TITLE
[BUG] Deadlock in bridge service

### ISSUE THREAD

**Issue by FedeParola** [polycube-network/polycube#300]
## Describe the bug
In bridge service a deadlock may occur when deleting a port while a packet is being processed in the slowpath.
Mutex `ports_mutex_` is acquired when removing a port https://github.com/polycube-network/polycube/blob/2e4f4e2081eca0322e4729434aff897a6cac84fa/src/services/pcn-bridge/src/Bridge.cpp#L154-L158
This function then calls function `Cube<PortType>::remove_port()` that acquires `cube_mutex` https://github.com/polycube-network/polycube/blob/2e4f4e2081eca0322e4729434aff897a6cac84fa/src/libs/polycube/include/polycube/services/cube.h#L153-L157

Packets coming from the fast path are processed acquiring those mutex in reverse order.
The callback acquires cube_mutex https://github.com/polycube-network/polycube/blob/2e4f4e2081eca0322e4729434aff897a6cac84fa/src/libs/polycube/include/polycube/services/cube.h#L69-L86
and method `broadcast()` of the bridge then acquires `ports_mutex_` https://github.com/polycube-network/polycube/blob/2e4f4e2081eca0322e4729434aff897a6cac84fa/src/services/pcn-bridge/src/Bridge.cpp#L111-L120
Causing a deadlock.

## To Reproduce
This is difficult to reproduce since it depends on timing.
I found it while running test `pcn-bridge/tests/vlan/test1.sh` on my PR #298

## Expected behavior
No deadlock should occur.

## Please tell us about your environment: 
1. OS details: Ubuntu 18.04 
2. Kernel details: 5.3.0

## Additional context
I think `ports_mutex_` can be safely removed.
As far as I understand both the mutex have the same function: avoid deleting a port while processing a packet from the fastpath

**Comment by frisso** [comment]
I completely agree.
Also from the point of a possible developer, concurrency in adding/removing a port should be handled by the framework, not in the control plane of the program itself.
I would remove `ports_mutex_` as well, given that a protection exists anyway.
Asking also @mauriciovasquezbernal what he thinks; he may have a more in-depth picture of the bridge.

**Comment by mauriciovasquezbernal** [comment]
I wasn't able to find it on the git history but I think `ports_mutex_` was implemented before `cube_mutex` and that's the reason why there is such a double logic. I think it's safe to remove it. 
Btw, there is also a `ports_mutex_` on the simple bridge that does nothing.

https://github.com/polycube-network/polycube/blob/16bcb4e45f7b3f49ad720a8583402a0ca62b91ac/src/services/pcn-simplebridge/src/Simplebridge.cpp#L103

**Comment by FedeParola** [comment]
Thank you @mauriciovasquezbernal, I will remove that mutex as well
