### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mnshrr** [polycube-network/polycube#309]
"make -j $(getconf _NPROCESSORS_ONLN)" failed with This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
## Describe the bug
"make -j $(getconf _NPROCESSORS_ONLN)" failed with attached error 
part of error:
[ 16%] Building CXX object src/libs/bcc/src/cc/CMakeFiles/bcc-loader-static.dir/bcc_syms.cc.o
Scanning dependencies of target xpath
[ 16%] Building CXX object src/polycubed/src/server/Parser/CMakeFiles/xpath.dir/XPathParserDriver.cpp.o
In file included from /usr/include/c++/5/typeindex:35:0,
                 from /home/ebpf/eBPF/polycube/src/polycubed/src/server/Parser/../Resources/Body/ListKey.h:22,
                 from /home/ebpf/eBPF/polycube/src/polycubed/src/server/Parser/XPathParserDriver.h:21,
                 from /home/ebpf/eBPF/polycube/src/polycubed/src/server/Parser/XPathParserDriver.cpp:16:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  `^
[polycube make error.txt](https://github.com/polycube-network/polycube/files/4699749/polycube.make.error.txt)
`

## To Reproduce
Follow the steps for installation here: https://polycube-network.readthedocs.io/en/latest/installation.html

## Expected behavior
Make complete with no error

## Please tell us about your environment: 
Environment :

1. OS details: `cat /etc/*-release` 
root@ebpf-VirtualBox:/etc# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@ebpf-VirtualBox:/etc# 

2. Kernel details: `uname -a`
root@ebpf-VirtualBox:/etc# uname -a
Linux ebpf-VirtualBox 4.15.0-99-generic #100~16.04.1-Ubuntu SMP Wed Apr 22 23:56:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@ebpf-VirtualBox:/etc# 

3. Polycube Version: `polycubectl version`
installing 

4. Polycube Log: Attach the log from `/var/log/polycube/polycubed.log`

**Comment by mauriciovasquezbernal** [comment]
You're using a too old version of Ubuntu. The installation suggests 18.04 and IIUC 20.04 works too.

**Comment by acloudiator** [comment]
@mnshrr Did you got a chance to validate it on Ubuntu 18.04 LTS or 20.04 LTS?

**Comment by mnshrr** [comment]
No, actually I still see error, this time:
polycube-0.9.0-rc$ ./scripts/install.sh 
Use 'install.sh -h' to show advanced installation options.
+ set -e
+++ dirname ./scripts/install.sh
++ cd ./scripts
++ pwd
+ DIR=/Polycube/polycube-0.9.0-rc/scripts
+ source scripts/pre-requirements.sh
++ '[' -z /Polycube/polycube-0.9.0-rc/scripts ']'
++ mkdir -p /home/mehrnaz/dev
++ sudo apt update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://ppa.launchpad.net/nemh/systemback/ubuntu xenial InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Ign:6 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal InRelease
Err:7 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/longsleep/golang-backports/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
+++ error_message
+++ set +x

Error during installation
***********************SYSTEM INFO*************************************
kernel version: 5.4.0-33-generic
linux release info: DISTRIB_ID=Ubuntu DISTRIB_RELEASE=20.04 DISTRIB_CODENAME=focal DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS" NAME="Ubuntu" VERSION="20.04 LTS (Focal Fossa)" ID=ubuntu ID_LIKE=debian PRETTY_NAME="Ubuntu 20.04 LTS" VERSION_ID="20.04" HOME_URL="https://www.ubuntu.com/" SUPPORT_URL="https://help.ubuntu.com/" BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/" PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy" VERSION_CODENAME=focal UBUNTU_CODENAME=focal
./scripts/install.sh: line 9: g++: command not found
g++ version:
gcc version: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0 Copyright (C) 2019 Free Software Foundation, Inc. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
./scripts/install.sh: line 11: go: command not found
golang-version:
mehrnaz@mehrnaz:/Polycube/polycube-0.9.0-rc$ 

trying on linux version 20

**Comment by FedeParola** [comment]
Hi @mnshrr, I was able to install polycube v0.9.0 without problems on a fresh Ubuntu Server 20.04.1 installation.
Looking at the error you get it seems like a temporary problem, have you tried reinstalling later?

**Comment by mnshrr** [comment]
Yes Federico, I was also able to install it later on. I switched to Ubuntu
20.04 ..
Not sure if I updated github or not, but thanks a lit for checking and
follow up!

Regards,
Mehrnaz
