### ISSUE TITLE
[BUG] Build polycubectl failed.

### ISSUE THREAD

**Issue by Mr-dot-lu** [polycube-network/polycube#322]
## Describe the bug
When I build polycubectl, occured following errors:
./install.sh 
+ set -e
+ echo 'installing polycubectl ...'
installing polycubectl ...
++ pwd
+ pwdir=/root/rpmbuild/SOURCES/polycube-0.9.0-rc/src/polycubectl
+ mkdir -p /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/
+ ln -f -s /root/rpmbuild/SOURCES/polycube-0.9.0-rc/src/polycubectl /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/
+ cd /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/polycubectl
+ go get ./...
go: cannot find main module; see 'go help modules'
++ error_message
++ set +x

Error during installation

## To Reproduce
1. wget  https://github.com/polycube-network/polycube/archive/v0.9.0-rc.tar.gz
2. 
tar -azxvf v0.9.0-rc.tar.gz
cd polycube-0.9.0-rc/src/polycubectl/
chmod 777 install.sh
dos2unix install.sh
3. ./install.sh

## Expected behavior
build polycubectl.

## Please tell us about your environment: 
1. OS details: EulerOS release 2.0 (SP9)
2. Kernel details: Linux hostname 4.19.90-2003.4.0.0036.oe1.aarch64 #1 SMP Mon Mar 23 19:06:43 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
3. Polycube Version:  polycube-0.9.0-rc
4. Polycube Log: none

## Additional context
If I go mod init.
The error information is:

./install.sh 
+ set -e
+ echo 'installing polycubectl ...'
installing polycubectl ...
++ pwd
+ pwdir=/root/rpmbuild/SOURCES/polycube-0.9.0-rc/src/polycubectl
+ mkdir -p /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/
+ ln -f -s /root/rpmbuild/SOURCES/polycube-0.9.0-rc/src/polycubectl /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/
+ cd /openEuler/goworkspace/src/github.com/polycube-network/polycube/src/polycubectl
+ go get ./...
go: finding github.com/iancoleman/orderedmap latest
build github.com/polycube-network/polycube/src/polycubectl: cannot load github.com/Jeffail/gabs2: cannot find module providing package github.com/Jeffail/gabs2
++ error_message
++ set +x

Error during installation

**Comment by acloudiator** [comment]
@Mr-dot-lu 
I would recommend to try the updated release, link below: 
https://github.com/polycube-network/polycube/releases/download/v0.9.0/polycube-v0.9.0.tar.gz

launch the automatic install script, after extracting the tarball (use -h to see the different installation modes)
`./scripts/install.sh`

**Comment by frisso** [comment]
The command issues is wrong. You should install using ./scripts/install.sh, not ./install.sh.
Documentation has been checked; the reported command there is correct. So, closing the issue.
