### ISSUE TITLE
[Feature Request] Firewall "FORWARD" policy should be renamed as "ACCEPT"

### ISSUE THREAD

**Issue by frisso** [polycube-network/polycube#334]
Given that the firewall is a transparent service, it doesn't forward anything; in fact, the forwarding is possibly done by the service the firewall is attached to.
So, for clarity it should be better to rename the FORWARD action into ACCEPT.

**Comment by FedeParola** [comment]
Added with https://github.com/polycube-network/polycube/pull/337
