### ISSUE TITLE
pcn-iptables/pxn-iptables-init-xdp[BUG]

### ISSUE THREAD

**Issue by liuuwqia** [polycube-network/polycube#344]
##ubuntu20.04/kernel 5.4 

##polycubectl version
polycubectl:
 version: v0.9.0+ [git: (branch/commit): master/b7758768-dirty]
polycubed:
 version: v0.9.0+ [git: (branch/commit): master/b7758768-dirty]

description:
I'm using the pcn-iptabls service, using the pcn-iptables init-xdp mode init, when I init (pcn-iptables init-xdp).I see from the log that there is the following problem, I wonder if it will affect?

[2020-10-19 15:55:35.634] [polycubed] [debug] XDP program compileed
Oct 19 15:55:36 newblackbox2 polycubed[48188]: [2020-10-19 15:55:36.246] [polycubed] [debug] XDP program compileed
Oct 19 15:55:36 newblackbox2 polycubed[48188]: /virtual/main.c:541:1: error: table already exists
Oct 19 15:55:36 newblackbox2 polycubed[48188]: BPF_TABLE_SHARED("percpu_array", int, u64, pkts_acceptestablished_Output, 1);
Oct 19 15:55:36 newblackbox2 polycubed[48188]: ^
Oct 19 15:55:36 newblackbox2 polycubed[48188]: /virtual/include/bcc/helpers.h:171:69: note: expanded from macro 'BPF_TABLE_SHARED'
Oct 19 15:55:36 newblackbox2 polycubed[48188]: BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries); \
Oct 19 15:55:36 newblackbox2 polycubed[48188]:                                                                     ^
Oct 19 15:55:36 newblackbox2 polycubed[48188]: /virtual/main.c:542:1: error: table already exists
Oct 19 15:55:36 newblackbox2 polycubed[48188]: BPF_TABLE_SHARED("percpu_array", int, u64, bytes_acceptestablished_Output, 1);
Oct 19 15:55:36 newblackbox2 polycubed[48188]: ^
Oct 19 15:55:36 newblackbox2 polycubed[48188]: /virtual/include/bcc/helpers.h:171:69: note: expanded from macro 'BPF_TABLE_SHARED'
Oct 19 15:55:36 newblackbox2 polycubed[48188]: BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries); \
Oct 19 15:55:36 newblackbox2 polycubed[48188]:                                                                     ^
Oct 19 15:55:36 newblackbox2 polycubed[48188]: 2 errors generated.
Oct 19 15:55:36 newblackbox2 polycubed[48188]: [2020-10-19 15:55:36.517] [Iptables] [pcn-iptables] [error] load err: failed to init ebpf program: Unable to initialize BPF program
Oct 19 15:55:37 newblackbox2 polycubed[48188]: [2020-10-19 15:55:37.003] [polycubed] [debug] XDP program compileed
Oct 19 15:55:37 newblackbox2 polycubed[48188]: [2020-10-19 15:55:37.471] [polycubed] [debug] XDP program compileed

**Comment by FedeParola** [comment]
Hi @liuuwqia, yes there is a problem and it will probably affect the TCP connection tracking.
The problem appeared after the introduction of emulated XDP egress in 4c29de83aad763d2999c4b7294eb55a6987f6667. I'll try to find a solution, thanks for your feedback.

**Comment by liuuwqia** [comment]
Hi，Federico

I have another problem：

For the PCN iptables init XDP mode, after init, the XDP program will be loaded on the network card that supports native. Then, when the message arrives at the network card eno1 with XDP program, the XDP program in the ingress direction will work. From the log, we can see that the data is redirected to the next network card eno2, but the data will be dropped by eno1. I don't know why.

In the same network card eno2 egress direction, go to TC BPF program, so the message can be forwarded, and PCN iptables is also effective.

I don't know whether the XDP program that causes the data stream not communicating is due to the mismatch between the kernel and the libbpf Library of BCC or other reasons

Trace can see that it has been redirected to the next port, but the data does not arrive at this port:
[cid:image001.png@01D6A78E.4436B940]

**Comment by liuuwqia** [comment]
For the PCN iptables init XDP mode, after init, the XDP program will be loaded on the network card that supports native. Then, when the message arrives at the network card eno1 with XDP program, the XDP program in the ingress direction will work. From the log, we can see that the data is redirected to the next network card eno2, but the data will be dropped by eno1. I don't know why

In the same network card eno2 egress direction, go to TC BPF program, so the message can be forwarded, and PCN iptables is also effective

eno1----》 eno2
