### ISSUE TITLE
[BUG] Cannot delete rule in NAT

### ISSUE THREAD

**Issue by lfjdhr123** [polycube-network/polycube#345]
## Describe the bug
Delete the rule in NAT will trigger the lost connection.

## To Reproduce
![image](https://user-images.githubusercontent.com/15117910/96516722-871ad900-121c-11eb-802e-aea71469fe1f.png)

## Expected behavior
The rule should be deleted

## Please tell us about your environment: 
OS details:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Kernel details: Linux fangjia 5.4.0-47-generic #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Polycube Version: v0.9.0+

**Comment by FedeParola** [comment]
Hi @lfjdhr123,
for what concerns the deletion of a single rule you should use the command:
`polycubectl nat1 rule snat entry del RULE_ID`
(note the addition of the `entry` key), there is a typo in the documentation.
For what concerns the deletion of all rules there is definitely a bug, I'll try to fix it, thank for reporting it!
