### ISSUE TITLE
nat Hook mount point

### ISSUE THREAD

**Issue by leguandemomotou** [polycube-network/polycube#391]
## Is your feature request related to a problem? Please describe.
hello,I have two questions I want to consult。1 nat Hook mount point is xdp or tc? 2 polycube Can be installed in centos?Can you give me a link to install centos？
think you very much

## Additional context
Add any other context that could help to understand the feature request more.

**Comment by frisso** [comment]
**Attach point**
Each Polycube function can be attached either to TC (default) or XDP hook points.
However, this looks not clearly stated in the documentation.
@pinoOgni Would you mind add a small section in the documentation (e.g., here https://polycube-network.readthedocs.io/en/latest/cubes.html) to explain how to select the attach point? Thanks!

** Install in CentOS **
We tested in Ubuntu, but likely this should work in CentOS as well. We suggest to use the same instructions already available or, in case of troubles, run the Docker version of Polycube. This has exactly the same characteristics of the standalone version, simply with a slightly more complicated command line (help here: https://polycube-network.readthedocs.io/en/latest/quickstart.html#docker)

**Comment by leguandemomotou** [comment]
ok，think you very much

**Comment by pinoOgni** [comment]
Closed in #395
