### ISSUE TITLE
[Documentation] Updating docker image for codegen

### ISSUE THREAD

**Issue by palanik1** [polycube-network/polycube#417]
The docker repo for codegen pointed to in https://github.com/polycube-network/polycube/blob/master/Documentation/developers/codegen.md needs to be updated from
```
docker pull polycubenets/polycube-codegen
```
 to
```
docker pull polycubenetwork/polycube-codegen 
```

**Comment by frisso** [comment]
@pinoOgni Actually, we should update the polycube-codegen repo to push the image into https://hub.docker.com/orgs/polycubenetworks. Can you take care of this?

**Comment by pinoOgni** [comment]
Hi @palanik1 thanks for the issue, I'll update the documentation

**Comment by frisso** [comment]
Updated polycube-codegen to point to the correct repo.
This issue has been superseded by the above change, so the link in the documentation is correct.
