### ISSUE TITLE
[BUG] Add a service through the command "polycubectl service add"

### ISSUE THREAD

**Issue by gianlu33** [polycube-network/polycube#88]
There is a problem in adding a service to the framework through the command `polycubectl service add`.
The same service works if i add it in _src/services/CMakeLists.txt_ and then reinstall polycube, so it is not a problem of the service itself.

Here a screenshot:
![screen](https://user-images.githubusercontent.com/36645341/54771379-6c7a1b80-4c05-11e9-8820-e73940f7719a.png)

**Comment by mauriciovasquezbernal** [comment]
The syntax of that command changed a little bit, the following example works for me:
`polycubectl services add name=helloworld uri=/usr/lib/libpcn-helloworld.so type=lib`.

I open a PR fixing the documentation https://github.com/polycube-network/polycube/pull/92.
