### ISSUE TITLE
Fix standalone service compilation

### ISSUE THREAD

**Issue by mauriciovasquezbernal** [polycube-network/polycube#91]
`libpolycube` provides a set of primitives used by the services to communicate with the framework.

Some includes paths are giving problems in the compilation of standalone services (services that are not shipped with polycube), in order to solve it a `pkg-config` configuration file for libpolycube should be created, so services know which libraries and include paths they should use.

**Comment by frisso** [comment]
Renamed from the original name "provide pkg-config for libpolycube" which didn't explain which was the problem.

**Comment by frisso** [comment]
Solved by #115 .
